name: eventure
description: "An app to create and search for events close to you to meet new people."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.0
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  firebase_core: any
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_datetime_picker_plus: ^2.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^5.3.1
  firebase_auth_platform_interface: ^7.4.10
  cloud_firestore_platform_interface: 6.5.1
  build_runner: ^2.3.3
  plugin_platform_interface: ^2.1.3

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
