// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUZqekkkjKj8Ll32b9Pb-1e70rQeVtVQ',
    appId: '1:143041749341:web:9531ed2639b278a44bc8b4',
    messagingSenderId: '143041749341',
    projectId: 'eventure-1844f',
    authDomain: 'eventure-1844f.firebaseapp.com',
    storageBucket: 'eventure-1844f.firebasestorage.app',
    measurementId: 'G-DDW73NZ3D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZLZWAWHlrH2d9iB9yDCXvjUyU2ptCp0',
    appId: '1:143041749341:android:7bff2be7c5ac140a4bc8b4',
    messagingSenderId: '143041749341',
    projectId: 'eventure-1844f',
    storageBucket: 'eventure-1844f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABYMe28IHb6ydSVoq99Wk8EY0DPzaIk-A',
    appId: '1:143041749341:ios:31819bb21173c84d4bc8b4',
    messagingSenderId: '143041749341',
    projectId: 'eventure-1844f',
    storageBucket: 'eventure-1844f.firebasestorage.app',
    iosBundleId: 'com.example.eventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABYMe28IHb6ydSVoq99Wk8EY0DPzaIk-A',
    appId: '1:143041749341:ios:31819bb21173c84d4bc8b4',
    messagingSenderId: '143041749341',
    projectId: 'eventure-1844f',
    storageBucket: 'eventure-1844f.firebasestorage.app',
    iosBundleId: 'com.example.eventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlUZqekkkjKj8Ll32b9Pb-1e70rQeVtVQ',
    appId: '1:143041749341:web:3a7e2a19f510c79e4bc8b4',
    messagingSenderId: '143041749341',
    projectId: 'eventure-1844f',
    authDomain: 'eventure-1844f.firebaseapp.com',
    storageBucket: 'eventure-1844f.firebasestorage.app',
    measurementId: 'G-NJ75K1Y4TH',
  );

}